### ISSUE TITLE
Translation of Gutenberg block attributes

### ISSUE THREAD

**Issue by derpaschi** [Supertext/polylang-supertext#10]
Currently it is not possible to translate block specific attributes. 

As an example, for the following block, only the content (and not the title) will be translatable:

```
<!-- wp:namespace/blockname {"title":"My fancy title"} -->
<div class="wp-block-namespace-blockman"><!-- wp:paragraph -->
<p>Some Text</p>
<!-- /wp:paragraph -->

<!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link" href="thelink">Read more</a></div>
<!-- /wp:button --></div>
<!-- /wp:namespace/blockname -->
``` 

In this example we'll get translations for `Some Text` and `Read more` - but not for `My fancy title`.

Is there any way to make this possible?

**Comment by rblaettler** [comment]
Do you have a running setup? If yes, could you send a Test order to Supertext and then give me the Order ID? Send it to remy AT supertext DOT ch

**Comment by derpaschi** [comment]
Hi @rblaettler any updates on this? Did you receive my email with the order id?

**Comment by rblaettler** [comment]
Yep, Heinrich did send you an update by mail. Didn’t get it?

**Comment by derpaschi** [comment]
Oh, yes. Sorry. It got lost in some gmail subfolders. Thank you!

**Comment by hmuralt** [comment]
We are currently working on this issue.

**Comment by derpaschi** [comment]
This is done and can be closed. Thank you.
