### ISSUE TITLE
PLL_PREFIX constant does not exist

### ISSUE THREAD

**Issue by ocean90** [Supertext/polylang-supertext#14]
It seems like Polylang no longer defines a `PLL_PREFIX ` constant causing a PHP warning

> Use of undefined constant PLL_PREFIX - assumed 'PLL_PREFIX' (this will throw an Error in a future version of PHP)
> wp-content/plugins/polylang-supertext/src/Supertext/Polylang/Core.php:154

This was recently changed in https://github.com/Supertext/polylang-supertext/commit/76cc852ba0ae7b1fa31847a5dce18c407019eb53, cc @hmuralt 

Current workaround: Add `define( 'PLL_PREFIX', 'pll_' );` to `wp-config.php`.

**Comment by rblaettler** [comment]
Thanks for the hint.
We built a new version of our plugin that is compatible with Polylang and WPML. But it's not 100% ready yet. Will make sure it's fixed there.

**Comment by hmuralt** [comment]
#19 Fix
