### ISSUE TITLE
Leverage translate.wordpress.org

### ISSUE THREAD

**Issue by swissspidy** [Supertext/polylang-supertext#3]
Once the plugin is properly internationalized (see https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/ for guidance), translations can be easily mantained on translate.wordpress.org, leveraging the powerful community of translators worldwide.

This would remove the need for shipping the translation files with the plugin, as new translations can easily be updated in WordPress.

**Comment by hmuralt** [comment]
Sounds great and very interesting. We will update our plugin then. 

Is there any (REST) API to manage translations? Can for example the wordpress.org API be used to add translations? Or only to get them?

**Comment by swissspidy** [comment]
Right now there's no such API to submit translations, but if there are translations coming from a third-party platform, you can upload `.po`/`.mo` files to import them.

**Comment by swissspidy** [comment]
Translation is already possible, see https://translate.wordpress.org/projects/wp-plugins/polylang-supertext/dev/de/default. You can upload all the existing translations there and then remove them from the plugin folder.

After that, you just need to get rid of the `polylang-supertext-langs` text domain. A plugin should only contain one single text domain, in this case `polylang-supertext`.
