### ISSUE TITLE
Polylang 2.6 & Block Editor Support

### ISSUE THREAD

**Issue by grappler** [Supertext/polylang-supertext#8]
Polylang 2.6 has moved the translation meta box to a new sidebar for the WordPress block editor(Gutenberg).

https://polylang.pro/polylang-pro-2-6-introduces-a-new-block-editor-plugin/

This means the request translation link is missing.
![image](https://user-images.githubusercontent.com/1785641/60836995-69606680-a1c7-11e9-8aca-dcb6aa2dc530.png)

**Comment by rblaettler** [comment]
Ok, we'll have a look at this asap. But our resident WordPress developer is currently a bit under water with other issues.

**Comment by hmuralt** [comment]
@grappler Thanks for the feedback!

Fixed with 8c8c132bdb1a8f373d3d10a022bcb30dc2ef0b14
