### ISSUE TITLE
Don't enqeue block editor script on posts screen or when classic editor is used

### ISSUE THREAD

**Issue by ocean90** [Supertext/polylang-supertext#9]
Currently, when visiting wp-admin/edit.php with [Query Monitor](https://querymonitor.com/) active, you get this warning:
![image](https://user-images.githubusercontent.com/617637/64728163-a9e7a380-d4da-11e9-9586-836a97583496.png)

The script gets enqueued in
https://github.com/Supertext/polylang-supertext/blob/5ff2a8eb9240c3e6a2bc38f9b1183030ee8768fc/src/Supertext/Polylang/Backend/AdminExtension.php#L124 and is registered in https://github.com/Supertext/polylang-supertext/blob/5ff2a8eb9240c3e6a2bc38f9b1183030ee8768fc/src/Supertext/Polylang/Core.php#L150

The issue is, that `PLL_PREFIX . 'block-editor-plugin'` doesn't exists until you are on the edit screen with the block editor active (and Polylang Pro installed).

The fix would be to enqueue the script only when `AdminExtension::isEditPostScreen()` and `WP_Screen::is_block_editor()` is true.

**Comment by hmuralt** [comment]
@ocean90 thanks for the detailed report.

The check for both the edit screen and block editor has been added (92a7323bce7db035a21ed8ae6be4ead08fefb0ec).
